# Generated by Django 5.2.5 on 2025-08-12 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/hero/'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_homepage_hero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_nav',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ServiceDetail',
        ),
    ]
