# Generated by Django 5.2.5 on 2025-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
