# Generated by Django 5.2.5 on 2025-08-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_heroslide_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars) shown in search results', max_length=160),
        ),
    ]
