# Generated by Django 5.2.5 on 2025-08-15 08:13

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('size_unit', models.CharField(choices=[('inch', 'Inch'), ('ft', 'Feet'), ('mm', 'Millimeter')], max_length=10)),
                ('message', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Message')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
