# Generated by Django 5.2.5 on 2025-08-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_quote_height_quote_length_quote_thickness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='service',
            field=models.CharField(max_length=255),
        ),
    ]
