# Generated by Django 5.2.5 on 2025-08-16 09:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_quote_message_alter_quote_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
    ]
