# Generated by Django 5.2.5 on 2025-09-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_service_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Products',
        ),
    ]
