# Generated by Django 5.2.5 on 2025-09-07 17:46

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_products_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default=django.utils.timezone.now, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
