# Generated by Django 5.2.5 on 2025-09-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_products_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='size_unit',
            field=models.CharField(blank=True, choices=[('inch', 'Inch'), ('ft', 'Feet'), ('mm', 'Millimeter')], max_length=10, null=True),
        ),
    ]
