# Generated by Django 5.2.5 on 2025-09-19 10:29

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_contactinfo_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars) shown in search results', max_length=160)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='products/hero/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text')),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=True)),
                ('show_in_homepage_hero', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
