# Generated by Django 5.2.5 on 2025-09-19 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_product_productgalleryimage_delete_contactinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='api.product'),
        ),
    ]
