# Generated by Django 5.2.5 on 2025-09-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_quote_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
