# Generated by Django 5.2.5 on 2025-08-27 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user_name',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=10),
        ),
    ]
