# Generated by Django 5.2.5 on 2025-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatmessage_sender_alter_chatroom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
